[versions]
java = "17" # must be an integer

kotlin = "1.9.22"
kotlin-fabric = "1.10.18+kotlin.1.9.22"
kotlin-forge = "4.10.0"

# Minecraft

minecraft = { strictly="1.20.1" }
parchment = "2023.09.03"

architectury = "9.2.14"
architectury-plugin = { require="[3.4, 3.5[" }
architectury-loom = { require="[1.5, 1.6[" }

fabric-loader = "0.14.21"
fabric-api = "0.85.0+1.20.1"

forge = "1.20.1-47.2.0"
forge-dependency = "47" # for mods.toml

# mods

hexcasting = "0.11.1-7-pre-636"
paucal = "0.6.0-pre-118"

patchouli = "1.20.1-84"
patchouli-fabric = "1.20.1-84-FABRIC" # thanks vazkii
patchouli-forge = "1.20.1-84-FORGE"

hexal = "0.3.0-2"
hexal-dependency = "0.3.0-2"

cardinalComponents = "5.2.1"
serializationHooks = "0.4.99999"
mixinExtras = "0.1.1"
trinkets = "3.7.0"
clothConfig = "11.1.106"
modMenu = "7.1.0"
caelus = "3.1.0+1.20"

# other non-Minecraft dependencies

findbugs-jsr305 = "3.0.2" # for @Nonnull
asm = "9.5"
dotenv = "2.0.0" # for template.env debugger keys
shadow = "7.1.2"
modPublish = "0.5.1"
pkpcpbp = "0.1.0-pre-87"

lsp4j = "0.23.0"
ktor = "2.3.10"

[bundles]
asm = ["asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util"]
# must contain all transitive deps so they can be included in the production jar
lsp4j = ["lsp4j", "lsp4j-debug", "lsp4j-jsonrpc", "lsp4j-jsonrpc-debug"]
ktor = ["ktor-network", "ktor-network-jvm", "ktor-utils-jvm", "ktor-io-jvm"]

[libraries]
kotlin-stdlib = { module="org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref="kotlin" }
kotlin-fabric = { module="net.fabricmc:fabric-language-kotlin", version.ref="kotlin-fabric" }
kotlin-forge  = { module="thedarkcolour:kotlinforforge", version.ref="kotlin-forge" }

minecraft = { module="com.mojang:minecraft", version.ref="minecraft" }
parchment = { module="org.parchmentmc.data:parchment-1.20.1", version.ref="parchment" }

architectury        = { module="dev.architectury:architectury", version.ref="architectury" }
architectury-forge  = { module="dev.architectury:architectury-forge", version.ref="architectury" }
architectury-fabric = { module="dev.architectury:architectury-fabric", version.ref="architectury" }

fabric-loader = { module="net.fabricmc:fabric-loader", version.ref="fabric-loader" }
fabric-api    = { module="net.fabricmc.fabric-api:fabric-api", version.ref="fabric-api" }

forge = { module="net.minecraftforge:forge", version.ref="forge" }

hexcasting-common = { module="at.petra-k.hexcasting:hexcasting-common-1.20.1", version.ref="hexcasting" }
hexcasting-fabric = { module="at.petra-k.hexcasting:hexcasting-fabric-1.20.1", version.ref="hexcasting" }
hexcasting-forge  = { module="at.petra-k.hexcasting:hexcasting-forge-1.20.1", version.ref="hexcasting" }

paucal-common = { module="at.petra-k.paucal:paucal-common-1.20.1", version.ref="paucal" }
paucal-fabric = { module="at.petra-k.paucal:paucal-fabric-1.20.1", version.ref="paucal" }
paucal-forge  = { module="at.petra-k.paucal:paucal-forge-1.20.1", version.ref="paucal" }

hexal-common = { module="libs:hexal-common-1.20.1", version.ref="hexal" }
hexal-fabric = { module="libs:hexal-fabric-1.20.1", version.ref="hexal" }
hexal-forge  = { module="libs:hexal-forge-1.20.1", version.ref="hexal" }

patchouli-xplat  = { module="vazkii.patchouli:Patchouli-xplat", version.ref="patchouli" }
patchouli-fabric = { module="vazkii.patchouli:Patchouli", version.ref="patchouli-fabric" }
patchouli-forge  = { module="vazkii.patchouli:Patchouli", version.ref="patchouli-forge" }

cardinalComponents = { module="dev.onyxstudios.cardinal-components-api:cardinal-components-api", version.ref="cardinalComponents" }
serializationHooks = { module="libs:serialization-hooks", version.ref="serializationHooks" }
mixinExtras        = { module="com.github.LlamaLad7:MixinExtras", version.ref="mixinExtras" }
trinkets           = { module="dev.emi:trinkets", version.ref="trinkets" }
modMenu            = { module="com.terraformersmc:modmenu", version.ref="modMenu" }
caelus             = { module="top.theillusivec4.caelus:caelus-forge", version.ref="caelus" }

clothConfig-common = { module="me.shedaniel.cloth:cloth-config", version.ref="clothConfig" }
clothConfig-fabric = { module="me.shedaniel.cloth:cloth-config-fabric", version.ref="clothConfig" }
clothConfig-forge  = { module="me.shedaniel.cloth:cloth-config-forge", version.ref="clothConfig" }

findbugs-jsr305 = { module="com.google.code.findbugs:jsr305", version.ref="findbugs-jsr305" }

asm          = { module="org.ow2.asm:asm", version.ref="asm" }
asm-analysis = { module="org.ow2.asm:asm-analysis", version.ref="asm" }
asm-commons  = { module="org.ow2.asm:asm-commons", version.ref="asm" }
asm-tree     = { module="org.ow2.asm:asm-tree", version.ref="asm" }
asm-util     = { module="org.ow2.asm:asm-util", version.ref="asm" }

lsp4j               = { module="org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref="lsp4j" }
lsp4j-debug         = { module="org.eclipse.lsp4j:org.eclipse.lsp4j.debug", version.ref="lsp4j" }
lsp4j-jsonrpc       = { module="org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version.ref="lsp4j" }
lsp4j-jsonrpc-debug = { module="org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc.debug", version.ref="lsp4j" }

ktor-network     = { module="io.ktor:ktor-network", version.ref="ktor" }
ktor-network-jvm = { module="io.ktor:ktor-network-jvm", version.ref="ktor" }
ktor-utils-jvm = { module="io.ktor:ktor-utils-jvm", version.ref="ktor" }
ktor-io-jvm = { module="io.ktor:ktor-io-jvm", version.ref="ktor" }

pkpcpbp = { module="at.petra-k.pkpcpbp:PKPCPBP", version.ref="pkpcpbp" }

[plugins]
kotlin-jvm = { id="org.jetbrains.kotlin.jvm", version.ref="kotlin" }

architectury      = { id="architectury-plugin", version.ref="architectury-plugin" }
architectury-loom = { id="dev.architectury.loom", version.ref="architectury-loom" }

dotenv     = { id="co.uzzu.dotenv.gradle", version.ref="dotenv" }
shadow     = { id="com.github.johnrengelman.shadow", version.ref="shadow" }
modPublish = { id="me.modmuss50.mod-publish-plugin", version.ref="modPublish" }
