name: Run CI/CD pipeline

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: write
      pages: read
    with:
      deploy-pages: ${{ github.event_name != 'pull_request' && contains(fromJson(vars.HEXDOC_BRANCHES), github.ref_name) }}
      release: false
